FROM python:3.10-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libomp-dev \
    glpk-utils \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
# Add missing packages from previous steps
RUN pip install --no-cache-dir joblib uvicorn lightgbm xgboost pulp prophet

# Copy the whole project
COPY . .

ENV PYTHONPATH=/app

EXPOSE 8000

CMD ["uvicorn", "deployment.api.app:app", "--host", "0.0.0.0", "--port", "8000"]
